FROM fedora:28 AS python3.3

# CircleCI required tools
RUN dnf install -y \
      git \
      openssh \
      tar \
      gzip \
      gpg \
      ca-certificates \
  && dnf clean all && rm -rf /var/cache/dnf/*

# Python versions
RUN dnf install -y \
      python33 \
  && dnf clean all && rm -rf /var/cache/dnf/* \
  && curl https://bootstrap.pypa.io/pip/3.3/get-pip.py | python3.3

# Other packages required for tests
RUN dnf install -y \
      bzip2 \
  && dnf clean all && rm -rf /var/cache/dnf/*

RUN pip3 install 'tox<3' 'virtualenv<16'

WORKDIR /tmp/work
ENTRYPOINT ["/bin/bash"]
