name: Test

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["python2.7", "python3.3", "python3.4", "python3.5", "python3.6", "python3.7", "python3.8", "python3.9", "python3.10", "pypy", "pypy3"]
    container:
      image: danielflook/python-minifier-build:${{ matrix.python }}-2022-04-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Test
        run: |
          git tag
          VERSION=$(python3 setup.py --version)
          sed -i "s/setup_requires=.*/version='$VERSION',/; s/use_scm_version=.*//" setup.py

          tox -r -e $(echo "${{ matrix.python }}" | tr -d .)
